### ISSUE TITLE
How not to show 42 days in a month?

### ISSUE THREAD

**Issue by pettomartino** [lelivrescolaire/react-light-calendar#10]
Hi, 
First of all, congrats for the work in this lib.

I saw this lib displays 42 days in a month (https://github.com/lelivrescolaire/react-light-calendar/blob/master/src/utils.js#L4)
Which some times shows unnecessary weeks, for example:
![image](https://user-images.githubusercontent.com/101433/84165249-63c07000-aa6b-11ea-856a-c3bbee8aa113.png)

![image](https://user-images.githubusercontent.com/101433/84165292-70dd5f00-aa6b-11ea-8033-7e225281a336.png)

I believe the common behaviour is to display until the end of last week.

Is there any way to configure it and show just until the end of last week?

**Comment by arncet** [comment]
Hi @pettomartino,
I'm actually working on the `v3.0.0`, i'll try to fix this issue before release this major version.

**Comment by pettomartino** [comment]
No worries. I was just doing some research to find a lib to replace our current calendar component. Won't need that so soon and I might be able to help with that if we decide to go for it. Keep your priorities.

**Comment by arncet** [comment]
Fixed https://github.com/lelivrescolaire/react-light-calendar/pull/11 @pettomartino  ;)

**Comment by pettomartino** [comment]
thanks @arncet .
I recommend updating the codesandbox example. 👍

**Comment by arncet** [comment]
Yep, thank @pettomartino
