### ISSUE TITLE
Can't click the left & right arrow to change month & year

### ISSUE THREAD

**Issue by hyderali007** [lelivrescolaire/react-light-calendar#6]
I have followed everything required through the API given and included the calendar into my project, everything works but I whenever I click the arrow at the top to change the month & year, the calendar doesn't respond / change the month & year.

**Comment by arncet** [comment]
Hi @hyderali007, 
It looks like it's a problem coming from the states update.
I will publish a fix asap

**Comment by arncet** [comment]
Fixed in `2.0.6` https://github.com/lelivrescolaire/react-light-calendar/pull/7

**Comment by hyderali007** [comment]
Thank you so much! it's working well now
